---
- name: Send out a slack message
  hosts: vservers
  gather_facts: True
  tasks:
    - debug: var=ansible_distribution
    - debug: msg={{ item.key }}={{ item.value }}
      with_dict: ansible_cmdline
